### ISSUE TITLE
Too many unused packages in src/

### ISSUE THREAD

**Issue by likit** [Rnewbie/PCM_Aromatase#1]
It seems like simply run packrat::init() saves all the installed packages on the machine in src/. Most of the packages are not used in the project. Could you find the way to tell packrat to save only packages used for the project?

**Comment by likit** [comment]
By the way, Saw, I think having separate csv files would be better than .Rdata because csv files can be viewed on github and manipulated by many tools that work on plain text.

**Comment by sawsimeon** [comment]
Yes yes, packrat is so cool. i like.  i already did. haha. OK, for the dataset, i will uploaded it as a csv files.
